--Part-5: Advanced Queries.

--Find the top 3 bestselling books (highest quantity sold).
SELECT TOP 3 b.title AS Book_Title, SUM(o.quantity) AS Total_Sold
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.title
ORDER BY total_sold DESC;

--List authors who have more than 2 books in the database.
SELECT a.name, COUNT(b.book_id) AS total_books
FROM Authors a
JOIN Books b ON a.author_id = b.author_id
GROUP BY a.name
HAVING COUNT(b.book_id) > 2;

--Display customers who never placed an order.
SELECT c.name
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

--Show the total revenue generated by each author.
SELECT a.name AS author_name,
       SUM(o.quantity * b.price) AS revenue
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
JOIN Authors a ON b.author_id = a.author_id
GROUP BY a.name;

--Create views for:
--                Books and their available stock.
--                Orders with customer names and book titles.

--Views for Books and their available stock.
CREATE VIEW BookStock AS
SELECT title, stock FROM Books;
GO
Select * from BookStock;
GO

--Views for Orders with customer names and book titles.
CREATE VIEW OrderDetails AS
SELECT o.order_id, c.name AS customer_name, b.title AS book_title,
       o.quantity, o.order_date
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Books b ON o.book_id = b.book_id;
GO
Select * from OrderDetails;
GO